---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Allow HTTP and HTTPS through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - '80'
    - '443'

- name: Install Certbot and Nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload Nginx

- name: Obtain SSL certificate with Certbot
  shell: |
    certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m {{ email_address }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Enable and start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
