- name: Create Prometheus user
  user:
    name: prometheus

- name: Set Prometheus version
  set_fact:
    prometheus_version: "2.52.0"

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Move binaries
  shell: mv /opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin/ && mv /opt/prometheus-{{ prometheus_version }}.linux-amd64/promtool /usr/local/bin/

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /var/lib/prometheus
    - /etc/prometheus
    - /etc/systemd/system/prometheus.service.d

- name: Upload Prometheus config
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      rule_files:
        - /etc/prometheus/alert.rules.yml

      alerting:
        alertmanagers:
          - static_configs:
              - targets: ['localhost:9093']

      scrape_configs:
        - job_name: 'node'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'node_exporter_web'
          static_configs:
            - targets: ['{{ web_server_private_ip }}:9100']
  notify: Restart Prometheus

- name: Upload Prometheus alert rules
  copy:
    src: alert_rules.yml
    dest: /etc/prometheus/alert.rules.yml
  notify: Restart Prometheus

- name: Ensure Prometheus systemd override directory exists
  file:
    path: /etc/systemd/system/prometheus.service.d
    state: directory
    mode: '0755'

- name: Set Prometheus systemd override with proper flags
  copy:
    dest: /etc/systemd/system/prometheus.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.external-url=/prometheus/ \
        --web.route-prefix=/
  notify:
    - Reload systemd
    - Restart Prometheus
    
- name: Create systemd service base unit
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target
      [Install]
      WantedBy=multi-user.target
  notify: Reload Systemd

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes
