---
- name: Setup Monitoring Server
  hosts: monitoring
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  
  vars_files:
  - terraform_outputs.yml
  vars:
    loki_url: "http://localhost:3100/loki/api/v1/push"
    domain_name: monitoring.blessedc.org
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    slack_webhook_url: "https://hooks.slack.com/services/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"

  roles:
    - { role: node_exporter, tags: ['node_exporter'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: alertmanager, tags: ['alertmanager'] }
    - { role: loki, tags: ['loki'] }
    - { role: fluentbit, tags: ['fluentbit'] }

- name: Configure web server
  hosts: web
  become: true

  vars_files:
  - terraform_outputs.yml
  vars:
    domain_name: monitoring.blessedc.org
  roles:
    - { role: webserver, tags: ['webserver'] }
    - { role: node_exporter, tags: ['web_node_exporter'] }
    - { role: fluentbit_web, tags: ['fluentbit_web'] }

- name: Configure Nginx Reverse Proxy
  hosts: monitoring
  become: true

  vars_files:
  - terraform_outputs.yml
  
  vars:
    domain_name: monitoring.blessedc.org
    email_address: oyewolefemi69@gmail.com

  roles:
    - { role: reverse_nginx, tags: ['reverse_nginx'] }



