---
- name: Setup Monitoring Server
  hosts: monitoring
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  vars_files:
    - terraform_outputs.yml
  
  vars:
    loki_url: "http://localhost:3100/loki/api/v1/push"
    
  roles:
    - { role: node_exporter, tags: ['node_exporter'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: alertmanager, tags: ['alertmanager'] }
    - { role: loki, tags: ['loki'] }
    - { role: fluentbit, tags: ['fluentbit'] }

- name: Configure web server
  hosts: web
  become: true

  roles:
    - { role: webserver, tags: ['webserver'] }
    - { role: node_exporter, tags: ['web_node_exporter'] }
    - { role: fluentbit_web, tags: ['fluentbit_web'] }

- name: Configure Nginx Reverse Proxy
  hosts: monitoring
  become: true

  roles:
    - { role: reverse_nginx, tags: ['reverse_nginx'] }



