- name: Download Loki
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.9.4/loki-linux-amd64.zip
    dest: /tmp/loki.zip

- name: Install unzip
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Unzip Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make Loki executable
  file:
    path: /usr/local/bin/loki-linux-amd64
    mode: '0755'
    state: file

- name: Rename Loki binary
  command: mv /usr/local/bin/loki-linux-amd64 /usr/local/bin/loki
  args:
    creates: /usr/local/bin/loki

- name: Create Loki config directory
  file:
    path: /etc/loki
    state: directory
    mode: '0755'

- name: Deploy Loki config
  copy:
    dest: /etc/loki/loki-config.yaml
    content: |
      auth_enabled: false

      server:
        http_listen_address: 0.0.0.0
        http_listen_port: 3100

      ingester:
        wal:
          enabled: true
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1

      schema_config:
        configs:
          - from: 2022-01-01
            store: boltdb-shipper
            object_store: s3
            schema: v11
            index:
              prefix: index_
              period: 24h

      storage_config:
        aws:
          s3: ${LOKI_BUCKET_NAME}
          region: ${LOKI_BUCKET_REGION}

        boltdb_shipper:
          active_index_directory: /tmp/loki/index
          cache_location: /tmp/loki/boltdb-cache
          shared_store: s3

        filesystem:
          directory: /tmp/loki/chunks

      compactor:
        working_directory: /tmp/loki/compactor

      limits_config:
        enforce_metric_name: false

      chunk_store_config:
        max_look_back_period: 0s

      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
  notify: Restart Loki

- name: Create systemd unit for Loki (with AWS creds from environment)
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki Log Aggregator
      After=network.target

      [Service]
      Environment=LOKI_BUCKET_NAME=s3://loki-logs-for-monitoring
      Environment=LOKI_BUCKET_REGION=us-east-1
      Environment=AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }}
      Environment=AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}
      ExecStart=/usr/local/bin/loki -config.file=/etc/loki/loki-config.yaml
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload Systemd
    - Restart Loki

- name: Create Loki storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - /tmp/loki
    - /tmp/loki/index
    - /tmp/loki/chunks
    - /tmp/loki/boltdb-cache
    - /tmp/loki/compactor

- name: Start and enable Loki
  systemd:
    name: loki
    enabled: yes
    state: started
